//! Live preview routes.
//!
//! **Preview iframe** (cookie-based, transparent proxy inside iframe):
//! - GET /preview/u/:slug            — owner preview (iframe + set cookie)
//! - GET /preview/s/:slug            — share preview (iframe + set cookie)
//!   Both set a `va_preview` cookie and render an iframe with `src="/"`.
//!   The iframe content is served by the cookie proxy fallback at root.
//!
//! **Markdown preview**:
//! - GET /md-preview/:slug           — rendered markdown page
//!
//! **Cookie proxy fallback** (root `/` handler):
//!   - Has cookie + from iframe → proxy to dev server
//!   - Has cookie + direct navigation (`Sec-Fetch-Dest: document`) → error page
//!   - No cookie → redirect to `/va/`
//!
//! Slugs are short-lived (5–10 min) and generated by the `preview` /
//! `md_preview` MCP tools. The slug itself acts as authentication.

use axum::{
    extract::{Path, Request, State},
    http::StatusCode,
    response::{IntoResponse, Redirect, Response},
};
use axum::body::Body;

use common::preview_entries::PreviewTarget;

use super::AppState;

// ===========================================================================
// Preview iframe — sets cookie, renders iframe with src="/"
// ===========================================================================

/// Cookie name for authenticated owner sessions (set by /pair flow).
const OWNER_COOKIE: &str = "va_owner";

/// GET /preview/u/{slug} — owner preview. Requires `va_owner` cookie.
///
/// Dispatches by session target: Server → iframe + cookie proxy,
/// File → rendered markdown. If the cookie is missing or invalid,
/// redirects to `/va/?next=<original-url>` so the pairing gate can
/// send the user back to their intended destination.
pub async fn owner_preview_handler(
    Path(slug): Path<String>,
    req: Request,
) -> Result<Response, (StatusCode, String)> {
    if !owner_cookie_valid(&req) {
        // `req.uri().path_and_query()` sees the path AFTER the `/va` nest
        // prefix has been stripped by axum, so prepend `/va` to rebuild the
        // absolute URL the browser should land on after pairing.
        let inner = req
            .uri()
            .path_and_query()
            .map(|pq| pq.as_str().to_string())
            .unwrap_or_else(|| format!("/preview/u/{}", slug));
        let next = format!("/va{}", inner);
        let location = format!("/va/?next={}", url_encode_query(&next));
        return Ok(Response::builder()
            .status(StatusCode::FOUND)
            .header("Location", location)
            .body(Body::empty())
            .unwrap());
    }
    render_preview(&slug).await
}

/// Minimal percent-encoder for query-string values: encodes anything
/// outside the unreserved set so the URL stays well-formed.
fn url_encode_query(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for b in s.as_bytes() {
        match b {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                out.push(*b as char);
            }
            _ => out.push_str(&format!("%{:02X}", b)),
        }
    }
    out
}

/// GET /preview/s/{slug} — share preview. Slug itself is the auth.
///
/// Dispatches by session target: Server → iframe + cookie proxy,
/// File → rendered markdown. No pairing required — the random share
/// key (10-min TTL) gates access.
pub async fn share_preview_handler(
    Path(slug): Path<String>,
) -> Result<Response, (StatusCode, String)> {
    render_preview(&slug).await
}

/// Check whether the request carries a valid `va_owner` cookie.
fn owner_cookie_valid(req: &Request) -> bool {
    let token = match extract_cookie(req, OWNER_COOKIE) {
        Some(t) => t,
        None => return false,
    };
    common::auth::read_token_file()
        .map(|f| f.token == token)
        .unwrap_or(false)
}

/// Look up a preview by slug and dispatch to the right renderer based on target.
async fn render_preview(slug: &str) -> Result<Response, (StatusCode, String)> {
    let entry = common::preview_entries::lookup(slug)
        .ok_or_else(|| (StatusCode::NOT_FOUND, "Preview not found or expired.".to_string()))?;

    match entry.target {
        PreviewTarget::Server { port } => render_server_iframe(slug, &entry, port).await,
        PreviewTarget::File => render_md_page(&entry).await,
    }
}

/// Render the iframe wrapper for a Server preview; sets `va_preview` cookie
/// so the root-level cookie proxy can route requests to `localhost:{port}`.
async fn render_server_iframe(
    slug: &str,
    entry: &common::preview_entries::PreviewEntry,
    port: u16,
) -> Result<Response, (StatusCode, String)> {
    let remaining_ms = remaining_millis(entry);
    let remaining_secs = (remaining_ms / 1000) as u64;
    let title = escape_html(&entry.title);
    let subtitle = format!(":{}", port);

    let cookie_value = format!(
        "{}={}; Path=/; Max-Age={}; SameSite=Lax",
        PREVIEW_COOKIE, slug, remaining_secs
    );

    let toolbar = toolbar_and_timer(
        &title,
        &subtitle,
        remaining_ms,
        r#"<button onclick="document.querySelector('iframe').src=document.querySelector('iframe').src">Refresh</button>"#,
    );
    let html = format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Preview — {title}</title>
<style>
  {toolbar_css}
  body {{ background: #111; }}
  iframe {{
    width: 100%;
    height: calc(100vh - 40px);
    border: 0;
    background: #fff;
  }}
</style>
</head>
<body>
{toolbar}
<iframe src="/"></iframe>
</body>
</html>"#,
        title = title,
        toolbar_css = TOOLBAR_CSS,
        toolbar = toolbar,
    );

    Ok(Response::builder()
        .status(StatusCode::OK)
        .header("Content-Type", "text/html; charset=utf-8")
        .header("Set-Cookie", cookie_value)
        .body(Body::from(html))
        .unwrap())
}

fn server_not_running_page(port: u16) -> Response {
    let html = format!(
        r#"<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Server not running</title>
<style>
  body {{ font-family: -apple-system, sans-serif; display: flex; align-items: center; justify-content: center; height: 100vh; margin: 0; background: #f5f5f5; color: #333; }}
  .card {{ text-align: center; padding: 40px; background: #fff; border-radius: 12px; box-shadow: 0 2px 12px rgba(0,0,0,0.08); max-width: 400px; }}
  .card h2 {{ margin-bottom: 8px; }}
  .card p {{ color: #666; line-height: 1.5; }}
  .port {{ font-family: monospace; background: #eee; padding: 2px 6px; border-radius: 4px; }}
</style></head>
<body><div class="card">
  <h2>Server not running</h2>
  <p>No server is responding on port <span class="port">{port}</span>.<br>
  The dev server may have stopped or not started yet.</p>
</div></body></html>"#,
        port = port,
    );
    Response::builder()
        .status(StatusCode::BAD_GATEWAY)
        .header("Content-Type", "text/html; charset=utf-8")
        .body(Body::from(html))
        .unwrap()
}

// ===========================================================================
// Markdown preview — rendered document page
// ===========================================================================

/// Legacy route: GET /md-preview/:slug → render markdown directly.
/// New clients use /preview/u/{slug} or /preview/s/{slug}; both dispatch
/// to [`render_md_page`] when the session target is `File`.
pub async fn md_preview_handler(
    Path(slug): Path<String>,
) -> Result<Response, (StatusCode, String)> {
    let entry = common::preview_entries::lookup(&slug)
        .ok_or_else(|| (StatusCode::NOT_FOUND, "Preview not found or expired.".to_string()))?;
    render_md_page(&entry).await
}

/// Render a markdown file preview with toolbar + GitHub CSS + marked.js.
async fn render_md_page(
    entry: &common::preview_entries::PreviewEntry,
) -> Result<Response, (StatusCode, String)> {
    let file_path = match &entry.target {
        PreviewTarget::File => &entry.id,
        PreviewTarget::Server { .. } => {
            return Err((StatusCode::BAD_REQUEST, "This preview serves a server, not a file.".to_string()));
        }
    };

    let content = tokio::fs::read_to_string(file_path).await.map_err(|e| {
        (StatusCode::INTERNAL_SERVER_ERROR, format!("Failed to read file: {e}"))
    })?;

    let remaining_ms = remaining_millis(entry);
    let title = escape_html(&entry.title);

    // Build subtitle: workspace_name / relative_path (or just filename)
    let ws_name = entry.workspace
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("");
    let subtitle = if let Ok(rel) = file_path.strip_prefix(&entry.workspace) {
        format!("{} / {}", escape_html(ws_name), escape_html(&rel.display().to_string()))
    } else {
        escape_html(ws_name).to_string()
    };

    // Escape the markdown for embedding in a JS template literal.
    let escaped_md = content
        .replace('\\', "\\\\")
        .replace('`', "\\`")
        .replace("${", "\\${")
        .replace("</script>", "<\\/script>");

    let toolbar = toolbar_and_timer(&title, &subtitle, remaining_ms, "");
    let html = format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/github-markdown-css@5/github-markdown-light.min.css">
<style>
  {toolbar_css}
  body {{
    background: #fff;
    color: #1f2328;
  }}
  .markdown-body {{
    max-width: 880px;
    margin: 0 auto;
    padding: 32px 24px 64px;
  }}
  @media (max-width: 767px) {{
    .markdown-body {{ padding: 16px; }}
  }}
  .markdown-body pre {{
    background: #f6f8fa;
    border-radius: 6px;
    padding: 16px;
    overflow-x: auto;
  }}
  .markdown-body code {{
    font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace;
    font-size: 85%;
  }}
  .markdown-body pre code {{
    background: transparent;
    padding: 0;
  }}
  .markdown-body table {{
    border-collapse: collapse;
    width: 100%;
  }}
  .markdown-body table th,
  .markdown-body table td {{
    border: 1px solid #d0d7de;
    padding: 6px 13px;
  }}
  .markdown-body table tr:nth-child(2n) {{
    background: #f6f8fa;
  }}
</style>
</head>
<body>
{toolbar}
<article class="markdown-body" id="content"></article>
<script src="https://cdn.jsdelivr.net/npm/marked@15/marked.min.js"></script>
<script>
(function() {{
  var raw = `{raw_md}`;
  document.getElementById('content').innerHTML = marked.parse(raw, {{ gfm: true }});
}})();
</script>
</body>
</html>"#,
        title = title,
        toolbar_css = TOOLBAR_CSS,
        toolbar = toolbar,
        raw_md = escaped_md,
    );
    Ok(html_response(html))
}

// ===========================================================================
// Shared utilities
// ===========================================================================

fn remaining_millis(entry: &common::preview_entries::PreviewEntry) -> u128 {
    entry.expires_at
        .saturating_duration_since(std::time::Instant::now())
        .as_millis()
}

fn escape_html(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

fn html_response(html: String) -> Response {
    Response::builder()
        .status(StatusCode::OK)
        .header("Content-Type", "text/html; charset=utf-8")
        .body(Body::from(html))
        .unwrap()
}

/// Toolbar HTML + countdown timer script.
fn toolbar_and_timer(title: &str, subtitle: &str, remaining_ms: u128, extra_buttons: &str) -> String {
    let subtitle_html = if subtitle.is_empty() {
        String::new()
    } else {
        format!(r#"<span class="subtitle">{}</span>"#, subtitle)
    };
    format!(
        r#"<div class="toolbar">
  <span class="title">{title}</span>
  {subtitle_html}
  <span class="badge" id="timer">5:00</span>
  <span class="spacer"></span>
  {extra_buttons}
</div>
<script>
(function() {{
  var expiry = Date.now() + {remaining_ms};
  var el = document.getElementById('timer');
  setInterval(function() {{
    var left = Math.max(0, expiry - Date.now());
    var m = Math.floor(left / 60000);
    var s = Math.floor((left % 60000) / 1000);
    el.textContent = m + ':' + (s < 10 ? '0' : '') + s;
    if (left <= 0) {{
      el.textContent = 'Expired';
      el.style.background = '#6b2020';
      el.style.color = '#e5a5a5';
    }}
  }}, 1000);
}})();
</script>"#,
        title = title,
        subtitle_html = subtitle_html,
        remaining_ms = remaining_ms,
        extra_buttons = extra_buttons,
    )
}

/// Toolbar CSS shared by all preview modes.
const TOOLBAR_CSS: &str = r#"
  * { margin: 0; padding: 0; box-sizing: border-box; }
  .toolbar {
    position: sticky;
    top: 0;
    z-index: 100;
    height: 40px;
    display: flex;
    align-items: center;
    gap: 12px;
    padding: 0 16px;
    background: #1a1a1a;
    border-bottom: 1px solid #333;
    font-size: 13px;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    color: #eee;
  }
  .toolbar .title {
    font-weight: 600;
    color: #fff;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
  .toolbar .subtitle {
    color: #999;
    font-size: 12px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
  .toolbar .badge {
    background: #2d6a4f;
    color: #b7e4c7;
    padding: 2px 8px;
    border-radius: 10px;
    font-size: 11px;
    flex-shrink: 0;
  }
  .toolbar .spacer { flex: 1; }
  .toolbar button {
    background: #333;
    color: #ccc;
    border: 1px solid #444;
    padding: 4px 12px;
    border-radius: 4px;
    cursor: pointer;
    font-size: 12px;
  }
  .toolbar button:hover { background: #444; color: #fff; }
"#;

// ===========================================================================
// Cookie-based preview proxy — transparent full-page dev-server proxy
// ===========================================================================

/// Cookie name used to route root-level requests to the dev server.
const PREVIEW_COOKIE: &str = "va_preview";

/// Fallback handler for root `/` — the cookie-based dev-server proxy.
///
/// Security rules:
/// - `/va/*` paths → serve dashboard SPA (never proxy)
/// - Has cookie + `Sec-Fetch-Dest: document` (direct navigation) → error page
/// - Has cookie + iframe/sub-resource context → proxy to dev server
/// - No cookie → redirect to `/va/`
pub async fn cookie_proxy_fallback(
    State(state): State<AppState>,
    req: Request,
) -> Response {
    // Never proxy /va/ paths — they belong to the dashboard.
    let path = req.uri().path();
    if path == "/va" || path.starts_with("/va/") {
        return super::spa_fallback(state.dist_for_fallback.clone()).await;
    }

    // Check Sec-Fetch-Dest: only allow iframe and sub-resource contexts.
    // Direct top-level navigation (or missing header, e.g. stripped by tunnel
    // proxy) is blocked. This is an allowlist — unknown values are rejected.
    let sec_fetch_dest = req
        .headers()
        .get("sec-fetch-dest")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("document"); // missing header → treat as direct navigation

    let is_allowed_context = matches!(
        sec_fetch_dest,
        "iframe" | "script" | "style" | "image" | "font" | "audio" | "video"
            | "empty"    // fetch() / XHR
            | "worker"   // Web Worker / Service Worker
            | "manifest" // Web App Manifest
    );
    let is_direct_navigation = !is_allowed_context;

    // Extract slug from cookie.
    let slug = extract_cookie(&req, PREVIEW_COOKIE);

    let slug = match slug {
        Some(s) => s,
        None => return Redirect::temporary("/va/").into_response(),
    };

    // Block direct navigation — preview content must only be accessed
    // inside an iframe wrapper. Redirect to dashboard instead of error page.
    if is_direct_navigation {
        return Redirect::temporary("/va/").into_response();
    }

    let entry = match common::preview_entries::lookup(&slug) {
        Some(e) => e,
        None => {
            // Cookie exists but entry expired — clear cookie and redirect.
            let clear_cookie = format!("{}=; Path=/; Max-Age=0; SameSite=Lax", PREVIEW_COOKIE);
            return Response::builder()
                .status(StatusCode::FOUND)
                .header("Location", "/va/")
                .header("Set-Cookie", clear_cookie)
                .body(Body::empty())
                .unwrap();
        }
    };

    let port = match &entry.target {
        PreviewTarget::Server { port } => *port,
        PreviewTarget::File => return preview_error_page(),
    };

    // Proxy the request to the dev server.
    let sub_path = req.uri().path().trim_start_matches('/');
    let query = req.uri().query().map(|q| format!("?{q}")).unwrap_or_default();

    // Try IPv4 first, then IPv6 loopback.
    let urls = [
        format!("http://127.0.0.1:{}/{}{}", port, sub_path, query),
        format!("http://[::1]:{}/{}{}", port, sub_path, query),
    ];

    let method = req.method().clone();
    let mut upstream_resp = None;

    for url in &urls {
        let upstream_req = state.preview_client.request(method.clone(), url);
        match upstream_req.send().await {
            Ok(resp) => {
                upstream_resp = Some(resp);
                break;
            }
            Err(e) if e.is_connect() => continue,
            Err(e) => {
                return (StatusCode::BAD_GATEWAY, format!("Upstream error: {e}")).into_response();
            }
        }
    }

    let upstream = match upstream_resp {
        Some(r) => r,
        None => return server_not_running_page(port),
    };

    let status = StatusCode::from_u16(upstream.status().as_u16())
        .unwrap_or(StatusCode::BAD_GATEWAY);

    let mut builder = Response::builder().status(status);

    // Forward safe response headers, strip framing-related ones.
    for (key, val) in upstream.headers() {
        let name = key.as_str().to_lowercase();
        match name.as_str() {
            // Strip headers that would break iframe embedding or leak info.
            "x-frame-options" | "content-security-policy" | "strict-transport-security" => {}
            // Forward everything else.
            _ => {
                builder = builder.header(key, val);
            }
        }
    }

    let body = match upstream.bytes().await {
        Ok(b) => b,
        Err(e) => {
            return (StatusCode::BAD_GATEWAY, format!("Failed to read upstream body: {e}")).into_response();
        }
    };

    builder.body(Body::from(body)).unwrap()
}

/// Extract a named cookie value from the request.
fn extract_cookie(req: &Request, name: &str) -> Option<String> {
    req.headers()
        .get_all("cookie")
        .iter()
        .filter_map(|v| v.to_str().ok())
        .flat_map(|s| s.split(';'))
        .map(|s| s.trim())
        .find_map(|pair| {
            let (k, v) = pair.split_once('=')?;
            if k.trim() == name {
                Some(v.trim().to_string())
            } else {
                None
            }
        })
}

/// Error page shown when a user directly navigates to a proxied path
/// outside of the iframe wrapper. Styled to match the dashboard's
/// Unauthorized page.
fn preview_error_page() -> Response {
    Response::builder()
        .status(StatusCode::FORBIDDEN)
        .header("Content-Type", "text/html; charset=utf-8")
        .body(Body::from(preview_error_html()))
        .unwrap()
}

fn preview_error_html() -> String {
    r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Preview — Access Denied</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    display: flex; align-items: center; justify-content: center;
    min-height: 100vh; padding: 24px;
    background: #09090b; color: #fafafa;
  }
  .card { max-width: 420px; width: 100%; }
  .badge {
    display: flex; align-items: center; gap: 12px;
    margin-bottom: 24px;
  }
  .badge .icon {
    width: 40px; height: 40px; border-radius: 8px;
    background: rgba(59, 130, 246, 0.1); color: #3b82f6;
    display: flex; align-items: center; justify-content: center;
  }
  .badge h1 { font-size: 16px; font-weight: 600; }
  .badge p { font-size: 12px; color: #71717a; }
  .info {
    border: 1px solid #27272a; border-radius: 8px;
    background: rgba(24, 24, 27, 0.5); padding: 16px;
    font-size: 14px; color: #a1a1aa; line-height: 1.6;
    margin-bottom: 24px;
  }
  .info p + p { margin-top: 12px; }
  .hint {
    font-size: 12px; font-weight: 500; text-transform: uppercase;
    letter-spacing: 0.05em; color: #71717a; margin-bottom: 8px;
  }
  ol { padding-left: 20px; font-size: 14px; color: rgba(250,250,250,0.9); }
  ol li { margin-bottom: 4px; }
  code { font-family: ui-monospace, monospace; font-size: 12px; }
  .footer {
    text-align: center; font-size: 10px; color: rgba(113,113,122,0.6);
    margin-top: 24px;
  }
</style>
</head>
<body>
<div class="card">
  <div class="badge">
    <div class="icon">
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"
           fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <circle cx="12" cy="12" r="10"/>
        <line x1="12" y1="8" x2="12" y2="12"/>
        <line x1="12" y1="16" x2="12.01" y2="16"/>
      </svg>
    </div>
    <div>
      <h1>Preview not available</h1>
      <p>This page can only be viewed inside a VibeAround preview frame.</p>
    </div>
  </div>
  <div class="info">
    <p>
      You've navigated directly to a preview proxy URL.
      For security, preview content is only accessible through the
      VibeAround preview iframe wrapper.
    </p>
    <p>
      If you had a preview link, it may have expired (links are valid for 5 minutes).
    </p>
  </div>
  <p class="hint">How to preview</p>
  <ol>
    <li>Ask your coding agent to run <code>preview</code> with the dev server port.</li>
    <li>Open the link the agent provides.</li>
  </ol>
  <p class="footer">VibeAround · preview links expire after 5 minutes</p>
</div>
</body>
</html>"#.to_string()
}
