//! Live preview routes — iframe wrapper + reverse proxy.
//!
//! - GET /preview/:slug       — HTML wrapper page with iframe + toolbar
//! - GET /preview/:slug/proxy — reverse proxy root to localhost:{port}
//! - GET /preview/:slug/proxy/*path — reverse proxy to localhost:{port}/{path}
//!
//! Slugs are short-lived (5 min) and generated by the `preview_start` MCP tool.
//! The slug itself acts as authentication — no bearer token required.

use axum::{
    extract::Path,
    http::StatusCode,
    response::Response,
};
use axum::body::Body;

/// GET /preview/:slug — HTML wrapper page with iframe pointing to /preview/:slug/proxy/
pub async fn wrapper_handler(
    Path(slug): Path<String>,
) -> Result<Response, (StatusCode, String)> {
    let entry = common::preview_entries::lookup(&slug)
        .ok_or_else(|| (StatusCode::NOT_FOUND, "Preview not found or expired.".to_string()))?;

    let title_escaped = entry.title.replace('<', "&lt;").replace('>', "&gt;").replace('"', "&quot;");
    let proxy_src = format!("/preview/{}/proxy/", slug);

    let html = format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Preview — {title}</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #111; color: #eee; }}
  .toolbar {{
    height: 40px;
    display: flex;
    align-items: center;
    gap: 12px;
    padding: 0 16px;
    background: #1a1a1a;
    border-bottom: 1px solid #333;
    font-size: 13px;
  }}
  .toolbar .title {{
    font-weight: 600;
    color: #fff;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }}
  .toolbar .badge {{
    background: #2d6a4f;
    color: #b7e4c7;
    padding: 2px 8px;
    border-radius: 10px;
    font-size: 11px;
    flex-shrink: 0;
  }}
  .toolbar .spacer {{ flex: 1; }}
  .toolbar button {{
    background: #333;
    color: #ccc;
    border: 1px solid #444;
    padding: 4px 12px;
    border-radius: 4px;
    cursor: pointer;
    font-size: 12px;
  }}
  .toolbar button:hover {{ background: #444; color: #fff; }}
  iframe {{
    width: 100%;
    height: calc(100vh - 40px);
    border: 0;
    background: #fff;
  }}
</style>
</head>
<body>
<div class="toolbar">
  <span class="title">{title}</span>
  <span class="badge" id="timer">5:00</span>
  <span class="spacer"></span>
  <button onclick="document.querySelector('iframe').src=document.querySelector('iframe').src">Refresh</button>
</div>
<iframe src="{proxy_src}"></iframe>
<script>
(function() {{
  var expiry = Date.now() + {remaining_ms};
  var el = document.getElementById('timer');
  setInterval(function() {{
    var left = Math.max(0, expiry - Date.now());
    var m = Math.floor(left / 60000);
    var s = Math.floor((left % 60000) / 1000);
    el.textContent = m + ':' + (s < 10 ? '0' : '') + s;
    if (left <= 0) {{
      el.textContent = 'Expired';
      el.style.background = '#6b2020';
      el.style.color = '#e5a5a5';
    }}
  }}, 1000);
}})();
</script>
</body>
</html>"#,
        title = title_escaped,
        proxy_src = proxy_src.replace('"', "&quot;"),
        remaining_ms = entry.expires_at.saturating_duration_since(std::time::Instant::now()).as_millis(),
    );

    Ok(Response::builder()
        .status(StatusCode::OK)
        .header("Content-Type", "text/html; charset=utf-8")
        .body(Body::from(html))
        .unwrap())
}

/// GET /preview/:slug/proxy/ — reverse proxy root to http://127.0.0.1:{port}/
pub async fn proxy_root_handler(
    Path(slug): Path<String>,
) -> Result<Response, (StatusCode, String)> {
    proxy_to_upstream(&slug, "").await
}

/// GET /preview/:slug/proxy/*path — reverse proxy to http://127.0.0.1:{port}/{path}
pub async fn proxy_handler(
    Path((slug, path)): Path<(String, String)>,
) -> Result<Response, (StatusCode, String)> {
    let sub_path = path.trim_start_matches('/');
    proxy_to_upstream(&slug, sub_path).await
}

/// Shared reverse proxy implementation.
async fn proxy_to_upstream(slug: &str, sub_path: &str) -> Result<Response, (StatusCode, String)> {
    let entry = common::preview_entries::lookup(slug)
        .ok_or_else(|| (StatusCode::NOT_FOUND, "Preview not found or expired.".to_string()))?;

    let target_url = format!("http://127.0.0.1:{}/{}", entry.port, sub_path);

    let client = reqwest::Client::builder()
        .redirect(reqwest::redirect::Policy::none())
        .build()
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;

    let upstream = match client.get(&target_url).send().await {
        Ok(resp) => resp,
        Err(e) if e.is_connect() => {
            return Ok(server_not_running_page(entry.port));
        }
        Err(e) => {
            return Err((StatusCode::BAD_GATEWAY, format!("Upstream error: {e}")));
        }
    };

    let status = StatusCode::from_u16(upstream.status().as_u16())
        .unwrap_or(StatusCode::BAD_GATEWAY);

    let mut builder = Response::builder().status(status);

    // Forward content-type and content-length headers
    if let Some(ct) = upstream.headers().get("content-type") {
        builder = builder.header("Content-Type", ct);
    }
    if let Some(cl) = upstream.headers().get("content-length") {
        builder = builder.header("Content-Length", cl);
    }
    // Forward cache-control for dev server assets
    if let Some(cc) = upstream.headers().get("cache-control") {
        builder = builder.header("Cache-Control", cc);
    }

    let body = upstream.bytes().await
        .map_err(|e| (StatusCode::BAD_GATEWAY, format!("Failed to read upstream body: {e}")))?;

    Ok(builder.body(Body::from(body)).unwrap())
}

/// Friendly error page when the dev server is not running.
fn server_not_running_page(port: u16) -> Response {
    let html = format!(
        r#"<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Preview — Server not running</title>
<style>
  body {{ font-family: -apple-system, sans-serif; display: flex; align-items: center; justify-content: center; height: 100vh; margin: 0; background: #f5f5f5; color: #333; }}
  .card {{ text-align: center; padding: 40px; background: #fff; border-radius: 12px; box-shadow: 0 2px 12px rgba(0,0,0,0.08); max-width: 400px; }}
  .card h2 {{ margin-bottom: 8px; }}
  .card p {{ color: #666; line-height: 1.5; }}
  .port {{ font-family: monospace; background: #eee; padding: 2px 6px; border-radius: 4px; }}
</style></head>
<body><div class="card">
  <h2>Server not running</h2>
  <p>No server is responding on port <span class="port">{port}</span>.<br>
  The dev server may have stopped or not started yet.</p>
</div></body></html>"#,
        port = port,
    );
    Response::builder()
        .status(StatusCode::BAD_GATEWAY)
        .header("Content-Type", "text/html; charset=utf-8")
        .body(Body::from(html))
        .unwrap()
}
