//! Live preview routes.
//!
//! **Preview iframe** (cookie-based, transparent proxy inside iframe):
//! - GET /preview/u/:slug            — owner preview (iframe + set cookie)
//! - GET /preview/s/:slug            — share preview (iframe + set cookie)
//!   Both set a `va_preview` cookie and render an iframe with `src="/"`.
//!   The iframe content is served by the cookie proxy fallback at root.
//!
//! **Markdown preview**:
//! - GET /md-preview/:slug           — rendered markdown page
//!
//! **Cookie proxy fallback** (root `/` handler):
//!   - Has cookie + from iframe → proxy to dev server
//!   - Has cookie + direct navigation (`Sec-Fetch-Dest: document`) → error page
//!   - No cookie → redirect to `/va/`
//!
//! Slugs are short-lived (TTL: `common::previews::SHARE_TTL_SECS`)
//! and generated by the `preview` / `md_preview` MCP tools. The slug
//! itself acts as authentication.
//!
//! ## Module layout
//!
//! - [`iframe`]        — `render_preview` dispatcher + server iframe wrapper
//! - [`markdown`]      — rendered markdown document page
//! - [`cookie_proxy`]  — root `/` fallback: transparent dev-server proxy
//! - [`toolbar`]       — shared toolbar HTML/CSS + HTML helpers

mod cookie_proxy;
mod iframe;
mod markdown;
mod toolbar;

use axum::body::Body;
use axum::extract::{Path, Request};
use axum::http::StatusCode;
use axum::response::Response;

pub use cookie_proxy::cookie_proxy_fallback;

use cookie_proxy::{extract_cookie, OWNER_COOKIE};
use iframe::render_preview;
use markdown::render_md_page;
use toolbar::url_encode_query;

// ===========================================================================
// Preview iframe — sets cookie, renders iframe with src="/"
// ===========================================================================

/// GET /preview/u/{slug} — owner preview. Requires `va_owner` cookie.
///
/// Dispatches by session target: Server → iframe + cookie proxy,
/// File → rendered markdown. If the cookie is missing or invalid,
/// redirects to `/va/?next=<original-url>` so the pairing gate can
/// send the user back to their intended destination.
pub async fn owner_preview_handler(
    Path(slug): Path<String>,
    req: Request,
) -> Result<Response, (StatusCode, String)> {
    if !owner_cookie_valid(&req) {
        // `req.uri().path_and_query()` sees the path AFTER the `/va` nest
        // prefix has been stripped by axum, so prepend `/va` to rebuild the
        // absolute URL the browser should land on after pairing.
        let inner = req
            .uri()
            .path_and_query()
            .map(|pq| pq.as_str().to_string())
            .unwrap_or_else(|| format!("/preview/u/{}", slug));
        let next = format!("/va{}", inner);
        let location = format!("/va/?next={}", url_encode_query(&next));
        return Ok(Response::builder()
            .status(StatusCode::FOUND)
            .header("Location", location)
            .body(Body::empty())
            .unwrap());
    }
    render_preview(&slug).await
}

/// GET /preview/s/{slug} — share preview. Slug itself is the auth.
///
/// Dispatches by session target: Server → iframe + cookie proxy,
/// File → rendered markdown. No pairing required — the random share
/// key (10-min TTL) gates access.
pub async fn share_preview_handler(
    Path(slug): Path<String>,
) -> Result<Response, (StatusCode, String)> {
    render_preview(&slug).await
}

/// Check whether the request carries a valid `va_owner` cookie.
fn owner_cookie_valid(req: &Request) -> bool {
    let token = match extract_cookie(req, OWNER_COOKIE) {
        Some(t) => t,
        None => return false,
    };
    common::auth::read_token_file()
        .map(|f| f.token == token)
        .unwrap_or(false)
}

// ===========================================================================
// Markdown preview — rendered document page
// ===========================================================================

/// Legacy route: GET /md-preview/:slug → render markdown directly.
/// New clients use /preview/u/{slug} or /preview/s/{slug}; both dispatch
/// to the markdown renderer when the session target is `File`.
pub async fn md_preview_handler(
    Path(slug): Path<String>,
) -> Result<Response, (StatusCode, String)> {
    let entry = common::previews::lookup(&slug).ok_or_else(|| {
        (
            StatusCode::NOT_FOUND,
            "Preview not found or expired.".to_string(),
        )
    })?;
    render_md_page(&entry).await
}
